### ISSUE TITLE
Any rpm equivalent project?

### ISSUE THREAD

**Issue by chook** [reines/dropwizard-debpkg-maven-plugin#13]
This project is awesome! In order to pack my dropwizard server to the world I want to be able to ship it with both deb and rpm packages.

I wanted to know if there's an RPM maven? (I tried rpm-maven-plugin but it is not as straight forward as this one)

**Comment by d-g** [comment]
This project is not ready to use yet.

When used for daemon, it’s just harmful now: it generates start-script in `/usr/bin/` that redirects error output of `.jar` into log, which is not subject to any kind of log-rotation, so it grows until system runs out of space.

Less serious but still not acceptable for proper Debian package issues are:

- Init-script’s (in `/etc/init.d/`) `stop` action (so `restart` too) sometimes does not work.
- Configs in `/etc/` (if any) are silently rewrited when upgrading.
- Purging is not fully implemented: it leaves unix user, that was created during installation.
- That user has home dir in `/home/`, while according to FHS `/var/lib/` should be used.
- Perhaps, something else.

**Comment by chook** [comment]
Thanks for the heads up!
I guess the issues you raised should be opened as different issues :)

**Comment by reines** [comment]
@d-g if you can open independent issues for these I'll take a look at them, or I'm more than happy to accept pull requests...

@chook thanks :) I'm afraid I've no idea about using RPMs with maven.
