### ISSUE TITLE
config question

### ISSUE THREAD

**Issue by grommitz** [reines/dropwizard-debpkg-maven-plugin#14]
Hi Jamie, thanks for this plugin its going to be really useful for me! I wanted to know how to use the configuration xml file listed in the README? Is it specified in the pom somehow or does it need a particular name or extension? I know nothing about making .deb files, sorry!

**Comment by grommitz** [comment]
sorry I didn't realise that it was the expanded version of the configuration for the plugin in the pom file! my bad

**Comment by reines** [comment]
No problem at all. If you have any further questions, just shout :)
