### ISSUE TITLE
add configuration files to DEBIAN/conffiles

### ISSUE THREAD

**Issue by msuret** [reines/dropwizard-debpkg-maven-plugin#18]
Hi Jamie, and thank you for the very good work which saved me a lot of time!
The problem I am facing is that every time I update the package with a new version, the jvm and yml configuration files are being replaced and all changes are lost.
Is there a way to add these files to DEBIAN/conffiles to avoid this ?
Thanks a lot !

**Comment by reines** [comment]
Hey. I've added support for this in #19. It will be in 0.9 once it is released. You should be able to get 0.9-SNAPSHOT from `oss.sonatype.org` if you need it sooner.
