### ISSUE TITLE
Add ability to customize deb package version

### ISSUE THREAD

**Issue by ochedru** [reines/dropwizard-debpkg-maven-plugin#20]
Using only the POM version is a bit restrictive. It would be nice to be able to add a timestamp or revision number (see `buildnumber-maven-plugin`) to distinguish between packages built from the same SNAPSHOT version.
```xml
<deb>
  <maintainer>foo</maintainer>
  <version>${project.version}.${buildNumber}</version>
</deb>
```

**Comment by reines** [comment]
Good idea. I've added an option for this that should be available in `0.10-SNAPSHOT`.
